### ISSUE TITLE
KS3.0 Internal Error

### ISSUE THREAD

**Issue by cnicy** [kubesphere/console#1249]
KS3.0 Internal Error
所有KS资源和K8S资源均正常运行（多集群场景），通过查看console日志报错信息如下：
```json
{ redis.set: Executed timeout 5000 ms
    at Timeout._onTimeout (/opt/kubesphere/console/server/server.js:64530:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  name: 'redis.set',
  args: 
   [ 'sid-08Z6K5EskGfJrjeZJeZgMqxZTQPOp2LU',
     '{"salt":"600rChtCnMyevb5p"}',
     'EX',
     7200000 ] }
  --> GET /login 200 5,015ms 14.82kb 2020/09/30T17:51:55.266
  <-- GET / 2020/09/30T17:52:00.247
{ UnauthorizedError: Not Login
    at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
    at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
    at renderView (/opt/kubesphere/console/server/server.js:23231:46)
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
  --> GET / 302 2ms 43b 2020/09/30T17:52:00.249
  <-- GET /login 2020/09/30T17:52:00.250
(node:16) UnhandledPromiseRejectionWarning: redis.info: Executed timeout 5000 ms
    at Timeout._onTimeout (/opt/kubesphere/console/server/server.js:64530:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3589)
`

**Comment by leoendless** [comment]
KS console needs to connect to a Redis server. The error shows the Redis connection timeout.

**Comment by cnicy** [comment]
closed
