### ISSUE TITLE
UnauthorizedError: Not Login error from ks-console

### ISSUE THREAD

**Issue by ensean** [kubesphere/console#1255]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**

Guide by the document, I deployed kubesphere on AWS EKS, the WebGUI of ks-console works as expect, but there are a lot of logs flushing from the ks-console pod

```shell
 --> GET / 302 1ms 43b 2020/10/14T09:42:02.311
  <-- GET /login 2020/10/14T09:42:02.311
  --> GET /login 200 9ms 14.82kb 2020/10/14T09:42:02.320
  <-- GET / 2020/10/14T09:42:12.309
{ UnauthorizedError: Not Login
    at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
    at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
    at renderView (/opt/kubesphere/console/server/server.js:23231:46)
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
  --> GET / 302 1ms 43b 2020/10/14T09:42:12.311
  <-- GET /login 2020/10/14T09:42:12.311
  --> GET /login 200 5ms 14.82kb 2020/10/14T09:42:12.316
  <-- GET / 2020/10/14T09:42:22.309
  --> GET / 302 2ms 43b 2020/10/14T09:42:22.311
{ UnauthorizedError: Not Login
    at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
    at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
    at renderView (/opt/kubesphere/console/server/server.js:23231:46)
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
  <-- GET /login 2020/10/14T09:42:22.312
  --> GET /login 200 7ms 14.82kb 2020/10/14T09:42:22.319
  <-- GET / 2020/10/14T09:42:32.310
```

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0
Kubernetes: 1.18

**Environment**
How many nodes and their hardware configuration: 

3 nodes 2c8g

(and other info are welcomed to help us debugging)

**To Reproduce**

**Expected behavior**

**Comment by ensean** [comment]
May be there is some flaw with the index page? Once I enter the index(/) page in the browser, this error is shown from the ks-console pod ...

**Comment by leoendless** [comment]
Thanks for your advice, the unnecessary error message should be removed.
