### ISSUE TITLE
本地无法运行代码

### ISSUE THREAD

**Issue by leowucn** [kubesphere/console#126]
2.1.0分支最新代码，本地Node版本1.13.7，yarn版本1.21.1。不知道是不是我的环境哪里有问题，请帮忙看下下面的错误，谢谢
```
$ yarn start
yarn run v1.21.1
$ concurrently -k --raw 'yarn dev:client' 'yarn dev:server'
$ cross-env NODE_ENV=development webpack-dev-server --config scripts/webpack.dev.js -w
$ cross-env NODE_ENV=development nodemon -w ./common -w ./server -e js,yaml server/server.js
[nodemon] 1.18.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: ./common /Users/wupeng/work/console_360/server/**/*
[nodemon] starting `node server/server.js`
Dashboard app running at port 8000
Happy[jsx]: Version: 5.0.1. Threads: 3
ℹ ｢wds｣: Project is running at http://0.0.0.0:8001/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/wupeng/work/console_360
Happy[jsx]: All set; signaling webpack to proceed.
✔ success webpack compiled in 581ms
✖ ｢wdm｣: Hash: 36f497e885671ccb4706
Version: webpack 4.41.4
Time: 667ms
Built at: 02/06/2020 5:54:37 PM
    Asset      Size  Chunks             Chunk Names
  main.js  33.5 KiB    main  [emitted]  main
vendor.js  1.31 MiB  vendor  [emitted]  vendor
Entrypoint main = vendor.js main.js
[0] multi (webpack)-dev-server/client?http://0.0.0.0:8001 (webpack)/hot/dev-server.js react-hot-loader/patch ./src/core/index.js 64 bytes {main} [built]
[./node_modules/react-hot-loader/dist/react-hot-loader.development.js] 97.1 KiB {vendor} [built]
[./node_modules/react-hot-loader/patch.js] 229 bytes {vendor} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8001] (webpack)-dev-server/client?http://0.0.0.0:8001 4.29 KiB {vendor} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {vendor} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.89 KiB {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {vendor} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {vendor} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {vendor} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {vendor} [built]
[./src/core/index.js] 881 bytes {main} [built] [failed] [1 error]
    + 46 hidden modules

ERROR in ./src/core/index.js
Module build failed (from ./node_modules/happypack/loader.js):
TypeError: Cannot read property 'concat' of undefined
    at findPath (/Users/wupeng/work/console_360/node_modules/babel-plugin-recharts/lib/index.js:55:26)
    at /Users/wupeng/work/console_360/node_modules/babel-plugin-recharts/lib/index.js:126:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/wupeng/work/console_360/node_modules/babel-plugin-recharts/lib/index.js:118:21)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
 @ multi react-hot-loader/patch ./src/core/index.js main[1]
ℹ ｢wdm｣: Failed to compile.

```

**Comment by leoendless** [comment]
nodejs 版本需要升到 10 以上

**Comment by leowucn** [comment]
@leoendless 不好意思，我的Nodejs版本写错了，是13.7.0。仍然有这个错

**Comment by leoendless** [comment]
应该是 yarn 安装的依赖与 node 13 不兼容的问题。
可以有两种方法：
1. 删除 yarn.lock ，重新执行 yarn install
2. node 版本切换到 10

**Comment by leowucn** [comment]
我装了12.15.0版本的Nodejs，现在可以了，谢谢
