### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by mingshun** [kubesphere/console#2186]
```
ks-console-6cfb754974-6n7j8# yarn start
yarn run v1.22.5
$ concurrently -k --raw 'yarn dev:client' 'yarn dev:server'
$ cross-env NODE_ENV=development webpack-dev-server --config scripts/webpack.dev.js -w
$ cross-env NODE_ENV=development nodemon -w ./common -w ./server -e js,yaml server/server.js
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): common server/**/*
[nodemon] watching extensions: js,yaml
[nodemon] starting `node server/server.js`
Dashboard app running at port 8000
Happy[jsx]: Version: 5.0.1. Threads: 3
ℹ ｢wds｣: Project is running at http://0.0.0.0:8001/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/nocalhost-dev
Happy[jsx]: All set; signaling webpack to proceed.
[hardsource:ecf49fa9] Writing new cache ecf49fa9...
[hardsource:ecf49fa9] Tracking node dependencies with: yarn.lock.
[HMR] Waiting for update signal from WDS...
[HMR] Waiting for update signal from WDS...
[HMR] Waiting for update signal from WDS...
[HMR] Waiting for update signal from WDS...
en 语言环境下重复UI词条为: App Store
en 语言环境下重复UI词条为: Discoveries
en 语言环境下重复UI词条为: Introduction
en 语言环境下重复UI词条为: New Apps
en 语言环境下重复UI词条为: Uncategorized
en 语言环境下重复UI词条为: App Description
en 语言环境下重复UI词条为: Application Name
en 语言环境下重复UI词条为: NAME
en 语言环境下重复UI词条为: ALIAS
en 语言环境下重复UI词条为: Latest Version
en 语言环境下重复UI词条为: Message
en 语言环境下重复UI词条为: None
en 语言环境下重复UI词条为: LOGGING
en 语言环境下重复UI词条为: Pods
en 语言环境下重复UI词条为: Grayscale Release
en 语言环境下重复UI词条为: TOTAL_COLLECTIONS
en 语言环境下重复UI词条为: Password
en 语言环境下重复UI词条为: Captcha
en 语言环境下重复UI词条为: Please input password
en 语言环境下重复UI词条为: Cluster Status
en 语言环境下重复UI词条为: INODE_USAGE
en 语言环境下重复UI词条为: CPU_USAGE
en 语言环境下重复UI词条为: MEMORY_USAGE
en 语言环境下重复UI词条为: NODES
en 语言环境下重复UI词条为: Network Policies
en 语言环境下重复UI词条为: CPU Utilization
en 语言环境下重复UI词条为: Memory Utilization
en 语言环境下重复UI词条为: Node Status
en 语言环境下重复UI词条为: DevOps Project
en 语言环境下重复UI词条为: Network Isolation
en 语言环境下重复UI词条为: Projects
en 语言环境下重复UI词条为: Service
en 语言环境下重复UI词条为: Usage
en 语言环境下重复UI词条为: DEVOPS_ADMIN_DESC
en 语言环境下重复UI词条为: Credentials Management
en 语言环境下重复UI词条为: Nodes Management
en 语言环境下重复UI词条为: Project Roles
en 语言环境下重复UI词条为: Roles
en 语言环境下重复UI词条为: Terminating
en 语言环境下重复UI词条为: CLUSTER_SETTINGS_DESC
en 语言环境下重复UI词条为: Last Message
en 语言环境下重复UI词条为: SECRET_NAME_TCAP
en 语言环境下重复UI词条为: ENTER_PORT_NUMBER
en 语言环境下重复UI词条为: PORT
en 语言环境下重复UI词条为: Invalid email
en 语言环境下重复UI词条为: Users
en 语言环境下重复UI词条为: Your password must meet the following requirements
en 语言环境下重复UI词条为: Review
en 语言环境下重复UI词条为: Versions
en 语言环境下重复UI词条为: Access Control
en 语言环境下重复UI词条为: Job Records
en 语言环境下重复UI词条为: Log
en 语言环境下重复UI词条为: LOGS
en 语言环境下重复UI词条为: No Limit
en 语言环境下重复UI词条为: Node IP
en 语言环境下重复UI词条为: Volumes
en 语言环境下重复UI词条为: EDIT
en 语言环境下重复UI词条为: projects
en 语言环境下重复UI词条为: MEMBER_CREATE_DESC
es 语言环境下重复UI词条为: App Store
es 语言环境下重复UI词条为: Discoveries
es 语言环境下重复UI词条为: Introduction
es 语言环境下重复UI词条为: New Apps
es 语言环境下重复UI词条为: Uncategorized
es 语言环境下重复UI词条为: App Description
es 语言环境下重复UI词条为: Application Name
es 语言环境下重复UI词条为: NAME
es 语言环境下重复UI词条为: ALIAS
es 语言环境下重复UI词条为: Latest Version
es 语言环境下重复UI词条为: Message
es 语言环境下重复UI词条为: None
es 语言环境下重复UI词条为: LOGGING
es 语言环境下重复UI词条为: Pods
es 语言环境下重复UI词条为: Grayscale Release
es 语言环境下重复UI词条为: TOTAL_COLLECTIONS
es 语言环境下重复UI词条为: Password
es 语言环境下重复UI词条为: Captcha
es 语言环境下重复UI词条为: Please input password
es 语言环境下重复UI词条为: Cluster Status
es 语言环境下重复UI词条为: INODE_USAGE
es 语言环境下重复UI词条为: NODES
es 语言环境下重复UI词条为: CPU_USAGE
es 语言环境下重复UI词条为: MEMORY_USAGE
es 语言环境下重复UI词条为: Network Policies
es 语言环境下重复UI词条为: CPU Utilization
es 语言环境下重复UI词条为: Memory Utilization
es 语言环境下重复UI词条为: Node Status
es 语言环境下重复UI词条为: DevOps Project
es 语言环境下重复UI词条为: Network Isolation
es 语言环境下重复UI词条为: Projects
es 语言环境下重复UI词条为: Service
es 语言环境下重复UI词条为: Usage
es 语言环境下重复UI词条为: DEVOPS_ADMIN_DESC
es 语言环境下重复UI词条为: Credentials Management
es 语言环境下重复UI词条为: Nodes Management
es 语言环境下重复UI词条为: Project Roles
es 语言环境下重复UI词条为: Roles
es 语言环境下重复UI词条为: Terminating
es 语言环境下重复UI词条为: CLUSTER_SETTINGS_DESC
es 语言环境下重复UI词条为: Last Message
es 语言环境下重复UI词条为: SECRET_NAME_TCAP
es 语言环境下重复UI词条为: ENTER_PORT_NUMBER
es 语言环境下重复UI词条为: PORT
es 语言环境下重复UI词条为: Invalid email
es 语言环境下重复UI词条为: Users
es 语言环境下重复UI词条为: Your password must meet the following requirements
es 语言环境下重复UI词条为: Review
es 语言环境下重复UI词条为: Versions
es 语言环境下重复UI词条为: Access Control
es 语言环境下重复UI词条为: Job Records
es 语言环境下重复UI词条为: Log
es 语言环境下重复UI词条为: No Limit
es 语言环境下重复UI词条为: Node IP
es 语言环境下重复UI词条为: Volumes
es 语言环境下重复UI词条为: EDIT
es 语言环境下重复UI词条为: CLUSTER_INFORMATION
es 语言环境下重复UI词条为: projects
es 语言环境下重复UI词条为: MEMBER_CREATE_DESC
es 语言环境下重复UI词条为: WORKSPACE_ROLE_DESC
tc 语言环境下重复UI词条为: App Store
tc 语言环境下重复UI词条为: Discoveries
tc 语言环境下重复UI词条为: New Apps
tc 语言环境下重复UI词条为: Uncategorized
tc 语言环境下重复UI词条为: Introduction
tc 语言环境下重复UI词条为: Application Name
tc 语言环境下重复UI词条为: App Description
tc 语言环境下重复UI词条为: NAME
tc 语言环境下重复UI词条为: Latest Version
tc 语言环境下重复UI词条为: ALIAS
tc 语言环境下重复UI词条为: None
tc 语言环境下重复UI词条为: LOGGING
tc 语言环境下重复UI词条为: Pods
tc 语言环境下重复UI词条为: Grayscale Release
tc 语言环境下重复UI词条为: Password
tc 语言环境下重复UI词条为: Captcha
tc 语言环境下重复UI词条为: Please input password
tc 语言环境下重复UI词条为: NODES
tc 语言环境下重复UI词条为: Cluster Status
tc 语言环境下重复UI词条为: INODE_USAGE
tc 语言环境下重复UI词条为: CPU_USAGE
tc 语言环境下重复UI词条为: MEMORY_USAGE
tc 语言环境下重复UI词条为: Network Policies
tc 语言环境下重复UI词条为: Node Status
tc 语言环境下重复UI词条为: CPU Utilization
tc 语言环境下重复UI词条为: Memory Utilization
tc 语言环境下重复UI词条为: Service
tc 语言环境下重复UI词条为: Projects
tc 语言环境下重复UI词条为: DevOps Project
tc 语言环境下重复UI词条为: Network Isolation
tc 语言环境下重复UI词条为: Usage
tc 语言环境下重复UI词条为: Roles
tc 语言环境下重复UI词条为: Terminating
tc 语言环境下重复UI词条为: Project Roles
tc 语言环境下重复UI词条为: Nodes Management
tc 语言环境下重复UI词条为: CLUSTER_SETTINGS_DESC
tc 语言环境下重复UI词条为: Credentials Management
tc 语言环境下重复UI词条为: Last Message
tc 语言环境下重复UI词条为: SECRET_NAME_TCAP
tc 语言环境下重复UI词条为: ENTER_PORT_NUMBER
tc 语言环境下重复UI词条为: PORT
tc 语言环境下重复UI词条为: Users
tc 语言环境下重复UI词条为: Invalid email
tc 语言环境下重复UI词条为: Your password must meet the following requirements
tc 语言环境下重复UI词条为: Versions
tc 语言环境下重复UI词条为: Review
tc 语言环境下重复UI词条为: Log
tc 语言环境下重复UI词条为: Node IP
tc 语言环境下重复UI词条为: Volumes
tc 语言环境下重复UI词条为: No Limit
tc 语言环境下重复UI词条为: Job Records
tc 语言环境下重复UI词条为: EDIT
tc 语言环境下重复UI词条为: Access Control
tc 语言环境下重复UI词条为: projects
tc 语言环境下重复UI词条为: WORKSPACE_ROLE_DESC
zh 语言环境下重复UI词条为: Application Name
zh 语言环境下重复UI词条为: App Description
zh 语言环境下重复UI词条为: NAME
zh 语言环境下重复UI词条为: Latest Version
zh 语言环境下重复UI词条为: ALIAS
zh 语言环境下重复UI词条为: LOGGING
zh 语言环境下重复UI词条为: Pods
zh 语言环境下重复UI词条为: Grayscale Release
zh 语言环境下重复UI词条为: Please input password
zh 语言环境下重复UI词条为: NODES
zh 语言环境下重复UI词条为: Cluster Status
zh 语言环境下重复UI词条为: CPU_USAGE
zh 语言环境下重复UI词条为: MEMORY_USAGE
zh 语言环境下重复UI词条为: INODE_USAGE
zh 语言环境下重复UI词条为: Network Policies
zh 语言环境下重复UI词条为: Node Status
zh 语言环境下重复UI词条为: CPU Utilization
zh 语言环境下重复UI词条为: Memory Utilization
zh 语言环境下重复UI词条为: CPU_USAGE
zh 语言环境下重复UI词条为: Service
zh 语言环境下重复UI词条为: Projects
zh 语言环境下重复UI词条为: DevOps Project
zh 语言环境下重复UI词条为: Network Isolation
zh 语言环境下重复UI词条为: Usage
zh 语言环境下重复UI词条为: Roles
zh 语言环境下重复UI词条为: Terminating
zh 语言环境下重复UI词条为: Project Roles
zh 语言环境下重复UI词条为: Nodes Management
zh 语言环境下重复UI词条为: CLUSTER_SETTINGS_DESC
zh 语言环境下重复UI词条为: Credentials Management
zh 语言环境下重复UI词条为: Last Message
zh 语言环境下重复UI词条为: SECRET_NAME_TCAP
zh 语言环境下重复UI词条为: ENTER_PORT_NUMBER
zh 语言环境下重复UI词条为: PORT
zh 语言环境下重复UI词条为: Users
zh 语言环境下重复UI词条为: Invalid email
zh 语言环境下重复UI词条为: Your password must meet the following requirements
zh 语言环境下重复UI词条为: Review
zh 语言环境下重复UI词条为: projects
zh 语言环境下重复UI词条为: WORKSPACE_ROLE_DESC

Compiling

● webpack █████████████████████████ building (15%) 42/44 modules 2 active
  src/core/terminal.js

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:

Compiling

● webpack █████████████████████████ building (40%) 257/292 modules 35 active
  node_modules/core-js/modules/es6.string.raw.js

Compiling

● webpack █████████████████████████ building (46%) 305/319 modules 14 active
  node_modules/core-js/modules/_string-pad.js

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Run from master branch. How to resolve this?

**Comment by harrisonliu5** [comment]
What is the version of Node in your current environment.  @mingshun

**Comment by mingshun** [comment]
> What is the version of Node in your current environment. @mingshun

v14.16.0

**Comment by harrisonliu5** [comment]
Please switch to 12.18.3 and try again.

**Comment by mingshun** [comment]
> Please switch to v12.18.3 and try again.

Still encounter the same error.

```
root@ks-console-bcd5bd58f-gnqkd:/home/nocalhost-dev# yarn start
yarn run v1.22.4
$ concurrently -k --raw 'yarn dev:client' 'yarn dev:server'
$ cross-env NODE_ENV=development nodemon -w ./common -w ./server -e js,yaml server/server.js
$ cross-env NODE_ENV=development webpack-dev-server --config scripts/webpack.dev.js -w
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): common server/**/*
[nodemon] watching extensions: js,yaml
[nodemon] starting `node server/server.js`
Dashboard app running at port 8000
Happy[jsx]: Version: 5.0.1. Threads: 3
ℹ ｢wds｣: Project is running at http://0.0.0.0:8001/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/nocalhost-dev
Happy[jsx]: All set; signaling webpack to proceed.
[hardsource:ecf49fa9] Writing new cache ecf49fa9...
[hardsource:ecf49fa9] Tracking node dependencies with: yarn.lock.
[HMR] Waiting for update signal from WDS...
[HMR] Waiting for update signal from WDS...
[HMR] Waiting for update signal from WDS...
[HMR] Waiting for update signal from WDS...

Compiling

● webpack █████████████████████████ building (15%) 42/44 modules 2 active
  src/core/terminal.js

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:

Compiling

● webpack █████████████████████████ building (40%) 229/257 modules 28 active
  node_modules/core-js/modules/es6.regexp.exec.js

Compiling

● webpack █████████████████████████ building (59%) 414/451 modules 37 active
  node_modules/lodash/toString.js

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
HappyWorker[jsx:2]: unable to send to master! Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:679:16)
    at processSend (/home/nocalhost-dev/node_modules/happypack/lib/processSend.js:8:15)
    at Object.UnbufferedFd.send (/home/nocalhost-dev/node_modules/happypack/lib/UnbufferedFd.js:9:3)
    at send (/home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:29:20)
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:47:11
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorker.js:36:7
    at apply (/home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:265:14)
    at /home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:283:9
    at /home/nocalhost-dev/node_modules/babel-loader/lib/index.js:59:71 {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
HappyWorker[jsx:2]: unable to send to master! Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:679:16)
    at processSend (/home/nocalhost-dev/node_modules/happypack/lib/processSend.js:8:15)
    at Object.UnbufferedFd.send (/home/nocalhost-dev/node_modules/happypack/lib/UnbufferedFd.js:9:3)
    at send (/home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:29:20)
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:47:11
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorker.js:36:7
    at apply (/home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:265:14)
    at /home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:283:9
    at /home/nocalhost-dev/node_modules/babel-loader/lib/index.js:59:71 {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@ks-console-bcd5bd58f-gnqkd:/home/nocalhost-dev# HappyWorker[jsx:1]: unable to send to master! Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:679:16)
    at processSend (/home/nocalhost-dev/node_modules/happypack/lib/processSend.js:8:15)
    at Object.UnbufferedFd.send (/home/nocalhost-dev/node_modules/happypack/lib/UnbufferedFd.js:9:3)
    at send (/home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:29:20)
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:47:11
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorker.js:36:7
    at apply (/home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:265:14)
    at /home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:283:9
    at /home/nocalhost-dev/node_modules/babel-loader/lib/index.js:59:71 {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
HappyWorker[jsx:1]: unable to send to master! Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:679:16)
    at processSend (/home/nocalhost-dev/node_modules/happypack/lib/processSend.js:8:15)
    at Object.UnbufferedFd.send (/home/nocalhost-dev/node_modules/happypack/lib/UnbufferedFd.js:9:3)
    at send (/home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:29:20)
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:47:11
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorker.js:36:7
    at apply (/home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:265:14)
    at /home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:283:9
    at /home/nocalhost-dev/node_modules/babel-loader/lib/index.js:59:71 {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
HappyWorker[jsx:0]: unable to send to master! Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:679:16)
    at processSend (/home/nocalhost-dev/node_modules/happypack/lib/processSend.js:8:15)
    at Object.UnbufferedFd.send (/home/nocalhost-dev/node_modules/happypack/lib/UnbufferedFd.js:9:3)
    at send (/home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:29:20)
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:47:11
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorker.js:36:7
    at apply (/home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:265:14)
    at /home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:283:9
    at /home/nocalhost-dev/node_modules/babel-loader/lib/index.js:59:71 {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
HappyWorker[jsx:0]: unable to send to master! Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:679:16)
    at processSend (/home/nocalhost-dev/node_modules/happypack/lib/processSend.js:8:15)
    at Object.UnbufferedFd.send (/home/nocalhost-dev/node_modules/happypack/lib/UnbufferedFd.js:9:3)
    at send (/home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:29:20)
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorkerChannel.js:47:11
    at /home/nocalhost-dev/node_modules/happypack/lib/HappyWorker.js:36:7
    at apply (/home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:265:14)
    at /home/nocalhost-dev/node_modules/happypack/lib/applyLoaders.js:283:9
    at /home/nocalhost-dev/node_modules/babel-loader/lib/index.js:59:71 {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

```

**Comment by harrisonliu5** [comment]
Maybe you can try typing the `npx browserslist@latest --update-db`, and you can get  more answers with https://stackoverflow.com/questions/55271798/browserslist-caniuse-lite-is-outdated-please-run-next-command-npm-update-cani

**Comment by sunjiesama** [comment]
Is it resolved? I also encountered the same problem
